name: Running Multiple Jobs

on: push

jobs:

  build_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Install Cowsay program
        run: sudo apt-get install cowsay -y

      - name: Execute Cowsay Command
        run: cowsay -f dragon "Run for cover, I am a dragon... RWARRR" >> dragon.txt

      - name: Upload the Dragon Text file
        uses: actions/upload-artifact@v3
        with:
            name: dragon-text-file
            path: dragon.txt

  test_job2:
    needs: build_job1
    runs-on: ubuntu-latest
    steps:
      - name: Download the Dragon Text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file


      - name: Test file exists
        run: grep -i "dragon" dragon.txt

  deploy_job3:
    needs: test_job2
    runs-on: ubuntu-latest
    steps:

      - name: Download the  Dragon Text file
        uses: actions/download-artifact@v3
        with:
          name: dragon-text-file


      - name: READ FILE
        run: cat dragon.txt

      - name: Print Hello
        run: echo "Successfully Deployed"